-- Add Post Office investment asset classes
ALTER TYPE "AssetClass" ADD VALUE IF NOT EXISTS 'NSC';
ALTER TYPE "AssetClass" ADD VALUE IF NOT EXISTS 'KVP';
ALTER TYPE "AssetClass" ADD VALUE IF NOT EXISTS 'SCSS';
ALTER TYPE "AssetClass" ADD VALUE IF NOT EXISTS 'SSY';
ALTER TYPE "AssetClass" ADD VALUE IF NOT EXISTS 'POST_OFFICE_MIS';
ALTER TYPE "AssetClass" ADD VALUE IF NOT EXISTS 'POST_OFFICE_RD';
ALTER TYPE "AssetClass" ADD VALUE IF NOT EXISTS 'POST_OFFICE_TD';
ALTER TYPE "AssetClass" ADD VALUE IF NOT EXISTS 'POST_OFFICE_SAVINGS';
