/**
 * AMC logo files, keyed by the slug `amcSlug()` derives from an AMC name.
 *
 * GENERATED by `scripts/normalise-amc-logos.py` — do not edit by hand.
 *
 * Each file is that fund house's own mark, fetched from its own site and
 * committed here rather than hot-linked. An <img> pointed at a third-party
 * logo service would put a request to someone else's server on every fund
 * page a reader opens, telling that service which funds this person is
 * researching, and would break the page when the service ends its free tier.
 *
 * An AMC absent from this map is not a bug — it renders the monogram, which
 * is the honest fallback. A wrong logo would be worse than initials.
 */
export const AMC_LOGOS: Readonly<Record<string, string>> = {
  '360-one': '/amc/360-one.png',  // 360 ONE Mutual Fund
  'abakkus': '/amc/abakkus.png',  // Abakkus Mutual Fund
  'aditya-birla-sun-life': '/amc/aditya-birla-sun-life.png',  // Aditya Birla Sun Life Mutual Fund
  'alphagrep': '/amc/alphagrep.png',  // AlphaGrep Mutual Fund
  'angel-one': '/amc/angel-one.png',  // Angel One Mutual Fund
  'ask': '/amc/ask.png',  // ASK MUTUAL FUND
  'axis': '/amc/axis.png',  // Axis Mutual Fund
  'bajaj-finserv': '/amc/bajaj-finserv.png',  // Bajaj Finserv Mutual Fund
  'bandhan': '/amc/bandhan.png',  // Bandhan Mutual Fund
  'bank-of-india': '/amc/bank-of-india.png',  // Bank of India Mutual Fund
  'baroda-bnp-paribas': '/amc/baroda-bnp-paribas.png',  // Baroda BNP Paribas Mutual Fund
  'canara-robeco': '/amc/canara-robeco.png',  // Canara Robeco Mutual Fund
  'capitalmind': '/amc/capitalmind.png',  // Capitalmind Mutual Fund
  'choice': '/amc/choice.png',  // Choice Mutual Fund
  'dsp': '/amc/dsp.png',  // DSP Mutual Fund
  'edelweiss': '/amc/edelweiss.png',  // Edelweiss Mutual Fund
  'franklin-templeton': '/amc/franklin-templeton.png',  // Franklin Templeton Mutual Fund
  'groww': '/amc/groww.png',  // Groww Mutual Fund
  'hdfc': '/amc/hdfc.png',  // HDFC Mutual Fund
  'helios': '/amc/helios.png',  // Helios Mutual Fund
  'hsbc': '/amc/hsbc.png',  // HSBC Mutual Fund
  'icici-prudential': '/amc/icici-prudential.svg',  // ICICI Prudential Mutual Fund
  'invesco': '/amc/invesco.png',  // Invesco Mutual Fund
  'iti': '/amc/iti.png',  // ITI Mutual Fund
  'jio-blackrock': '/amc/jio-blackrock.png',  // Jio BlackRock Mutual Fund
  'jm-financial': '/amc/jm-financial.png',  // JM Financial Mutual Fund
  'kotak-mahindra': '/amc/kotak-mahindra.png',  // Kotak Mahindra Mutual Fund
  'lic': '/amc/lic.png',  // LIC Mutual Fund
  'mahindra-manulife': '/amc/mahindra-manulife.png',  // Mahindra Manulife Mutual Fund
  'mirae-asset': '/amc/mirae-asset.png',  // Mirae Asset Mutual Fund
  'motilal-oswal': '/amc/motilal-oswal.png',  // Motilal Oswal Mutual Fund
  'navi': '/amc/navi.png',  // Navi Mutual Fund
  'nippon-india': '/amc/nippon-india.png',  // Nippon India Mutual Fund
  'nj': '/amc/nj.png',  // NJ Mutual Fund
  'old-bridge': '/amc/old-bridge.png',  // Old Bridge Mutual Fund
  'pgim-india': '/amc/pgim-india.png',  // PGIM India Mutual Fund
  'ppfas': '/amc/ppfas.png',  // PPFAS Mutual Fund
  'quant': '/amc/quant.png',  // quant Mutual Fund
  'quantum': '/amc/quantum.png',  // Quantum Mutual Fund
  'sbi': '/amc/sbi.png',  // SBI Mutual Fund
  'shriram': '/amc/shriram.png',  // Shriram Mutual Fund
  'sundaram': '/amc/sundaram.png',  // Sundaram Mutual Fund
  'tata': '/amc/tata.png',  // Tata Mutual Fund
  'taurus': '/amc/taurus.png',  // Taurus Mutual Fund
  'the-wealth-company': '/amc/the-wealth-company.png',  // The Wealth Company Mutual Fund
  'trust': '/amc/trust.png',  // Trust Mutual Fund
  'unifi': '/amc/unifi.png',  // Unifi Mutual Fund
  'union': '/amc/union.png',  // Union Mutual Fund
  'uti': '/amc/uti.png',  // UTI Mutual Fund
  'whiteoak-capital': '/amc/whiteoak-capital.png',  // WhiteOak Capital Mutual Fund
  'zerodha': '/amc/zerodha.png',  // Zerodha Mutual Fund
};
