import { api } from './client';
import type { ApiResponse } from '@everypaisa/shared';

function unwrap<T>(data: ApiResponse<T>): T {
  if (!data.success) throw new Error(data.error);
  return data.data;
}

export type AccountType = 'ASSET' | 'LIABILITY' | 'INCOME' | 'EXPENSE' | 'EQUITY';
export type VoucherType = 'JOURNAL' | 'PAYMENT' | 'RECEIPT' | 'CONTRA' | 'PURCHASE' | 'SALES';

export interface AccountNode {
  id: string;
  code: string;
  name: string;
  type: AccountType;
  parentId: string | null;
  openingBalance: string;
  children: AccountNode[];
}

export interface AccountFlat {
  id: string;
  code: string;
  name: string;
  type: AccountType;
  parentId: string | null;
  openingBalance: string;
}

export interface VoucherEntryDTO {
  id: string;
  debitAccountId: string;
  debitAccountCode: string;
  debitAccountName: string;
  creditAccountId: string;
  creditAccountCode: string;
  creditAccountName: string;
  amount: string;
  narration: string | null;
  transactionId: string | null;
}

export interface VoucherDTO {
  id: string;
  type: VoucherType;
  voucherNo: string;
  date: string;
  narration: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
  entries: VoucherEntryDTO[];
}

export interface LedgerEntry {
  date: string;
  voucherId: string;
  voucherNo: string;
  voucherType: VoucherType;
  narration: string | null;
  debit: string | null;
  credit: string | null;
  balance: string;
}

export interface LedgerResult {
  account: { id: string; code: string; name: string; type: AccountType };
  openingBalance: string;
  entries: LedgerEntry[];
  closingBalance: string;
}

export interface TrialBalanceRow {
  accountId: string;
  code: string;
  name: string;
  type: AccountType;
  openingBalance: string;
  totalDebit: string;
  totalCredit: string;
  closingBalance: string;
}

export interface PnLResult {
  income: TrialBalanceRow[];
  expense: TrialBalanceRow[];
  totalIncome: string;
  totalExpense: string;
  netProfit: string;
}

export interface BalanceSheetResult {
  assets: TrialBalanceRow[];
  liabilities: TrialBalanceRow[];
  equity: TrialBalanceRow[];
  retainedEarnings: string;
  totalAssets: string;
  /** Opening balances that don't net to zero: positive = liabilities side short. */
  openingDifference?: string;
  totalLiabilities: string;
  totalEquity: string;
}

export interface VoucherEntryInput {
  debitAccountId: string;
  creditAccountId: string;
  amount: string;
  narration?: string;
}

export interface CreateVoucherInput {
  type: VoucherType;
  voucherNo: string;
  date: string;
  narration?: string;
  entries: VoucherEntryInput[];
}

export const accountingApi = {
  async getAccountsTree(): Promise<AccountNode[]> {
    const { data } = await api.get<ApiResponse<AccountNode[]>>('/api/accounting/accounts/tree');
    return unwrap(data);
  },
  async getAccountsFlat(): Promise<AccountFlat[]> {
    const { data } = await api.get<ApiResponse<AccountFlat[]>>('/api/accounting/accounts/flat');
    return unwrap(data);
  },
  async createAccount(payload: { code: string; name: string; type: AccountType; parentId?: string | null; openingBalance?: string }): Promise<AccountFlat> {
    const { data } = await api.post<ApiResponse<AccountFlat>>('/api/accounting/accounts', payload);
    return unwrap(data);
  },
  async updateAccount(id: string, payload: Partial<{ code: string; name: string; type: AccountType; parentId: string | null; openingBalance: string }>): Promise<AccountFlat> {
    const { data } = await api.patch<ApiResponse<AccountFlat>>(`/api/accounting/accounts/${id}`, payload);
    return unwrap(data);
  },
  async deleteAccount(id: string): Promise<void> {
    await api.delete(`/api/accounting/accounts/${id}`);
  },

  async listVouchers(params?: { from?: string; to?: string; type?: VoucherType; page?: number; limit?: number }): Promise<{ vouchers: VoucherDTO[]; total: number; page: number; limit: number }> {
    const { data } = await api.get<ApiResponse<{ vouchers: VoucherDTO[]; total: number; page: number; limit: number }>>('/api/accounting/vouchers', { params });
    return unwrap(data);
  },
  async getVoucher(id: string): Promise<VoucherDTO> {
    const { data } = await api.get<ApiResponse<VoucherDTO>>(`/api/accounting/vouchers/${id}`);
    return unwrap(data);
  },
  async nextVoucherNo(type: VoucherType): Promise<string> {
    const { data } = await api.get<ApiResponse<{ voucherNo: string }>>('/api/accounting/vouchers/next-no', { params: { type } });
    return unwrap(data).voucherNo;
  },
  async createVoucher(payload: CreateVoucherInput): Promise<VoucherDTO> {
    const { data } = await api.post<ApiResponse<VoucherDTO>>('/api/accounting/vouchers', payload);
    return unwrap(data);
  },
  async updateVoucher(id: string, payload: Partial<CreateVoucherInput>): Promise<VoucherDTO> {
    const { data } = await api.patch<ApiResponse<VoucherDTO>>(`/api/accounting/vouchers/${id}`, payload);
    return unwrap(data);
  },
  async deleteVoucher(id: string): Promise<void> {
    await api.delete(`/api/accounting/vouchers/${id}`);
  },

  async getLedger(accountId: string, params?: { from?: string; to?: string }): Promise<LedgerResult> {
    const { data } = await api.get<ApiResponse<LedgerResult>>(`/api/accounting/ledger/${accountId}`, { params });
    return unwrap(data);
  },

  async getTrialBalance(asOf?: string): Promise<TrialBalanceRow[]> {
    const { data } = await api.get<ApiResponse<TrialBalanceRow[]>>('/api/accounting/reports/trial-balance', { params: { asOf } });
    return unwrap(data);
  },
  async getPnL(from?: string, to?: string): Promise<PnLResult> {
    const { data } = await api.get<ApiResponse<PnLResult>>('/api/accounting/reports/pnl', { params: { from, to } });
    return unwrap(data);
  },
  async getBalanceSheet(asOf?: string): Promise<BalanceSheetResult> {
    const { data } = await api.get<ApiResponse<BalanceSheetResult>>('/api/accounting/reports/balance-sheet', { params: { asOf } });
    return unwrap(data);
  },

  async suggestVoucherForTransaction(txnId: string): Promise<Partial<CreateVoucherInput> & { transactionId: string }> {
    const { data } = await api.get<ApiResponse<Partial<CreateVoucherInput> & { transactionId: string }>>(`/api/accounting/suggest/transaction/${txnId}`);
    return unwrap(data);
  },

  async generateFromActivity(): Promise<{ created: number; skipped: number; errors: number; total: number }> {
    const { data } = await api.post<ApiResponse<{ created: number; skipped: number; errors: number; total: number }>>('/api/accounting/generate-from-activity');
    return unwrap(data);
  },
  // ── Receipts ────────────────────────────────────────────────────────
  //
  // The same voucher as a document. `view` opens it in a tab (the server
  // sends it inline); `download` saves it. Both hit one endpoint one header
  // apart, so the thing you looked at is the thing you filed.

  /** Opens the receipt in a new tab. Returns the object URL's revoke handle. */
  async viewReceipt(voucherId: string): Promise<void> {
    const res = await api.get(`/api/accounting/vouchers/${voucherId}/receipt.pdf`, {
      params: { inline: 'true' },
      responseType: 'blob',
    });
    const url = URL.createObjectURL(res.data as Blob);
    window.open(url, '_blank', 'noopener');
    // Not revoked immediately: the new tab still needs to read it. Browsers
    // release it when the document that owns it is discarded.
    setTimeout(() => URL.revokeObjectURL(url), 60_000);
  },

  async downloadReceipt(voucherId: string, fileName: string): Promise<void> {
    const res = await api.get(`/api/accounting/vouchers/${voucherId}/receipt.pdf`, {
      responseType: 'blob',
    });
    saveBlob(res.data as Blob, fileName);
  },

  async downloadReceiptBundle(
    format: 'zip' | 'xlsx',
    params: { from?: string; to?: string; type?: VoucherType } = {},
  ): Promise<void> {
    const res = await api.get(`/api/accounting/receipts.${format}`, {
      params,
      responseType: 'blob',
    });
    saveBlob(res.data as Blob, `receipts.${format}`);
  },
};

/** Save a blob under a filename, the way every other download here does. */
function saveBlob(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

