/**
 * Bank logos and brand colours, keyed by `bankSlug()` of the display name.
 *
 * GENERATED by `scripts/fetch-bank-logos.py` — do not edit by hand; add a
 * COLOR_OVERRIDES / REJECT_URLS entry in the script instead.
 *
 * Logos are each bank's own image, fetched from its own domain and
 * committed rather than hot-linked. Colours are measured from the logo
 * pixels (dominant saturated hue + a second distinct hue when present).
 * A bank missing here renders initials and a neutral tile — a guessed
 * logo or colour would be worse.
 */
export interface BankBrandAsset {
  logo: string | null;
  color: string | null;
  accent: string | null;
}

export const BANK_BRAND_ASSETS: Readonly<Record<string, BankBrandAsset>> = {
  'airtel-payments-bank': { logo: '/banks/airtel-payments-bank.png', color: '#ec1b24', accent: null },
  'au-small-finance-bank': { logo: '/banks/au-small-finance-bank.png', color: '#eb691f', accent: '#6d276d' },
  'axis-bank': { logo: '/banks/axis-bank.png', color: '#97144d', accent: null },
  'bandhan-bank': { logo: '/banks/bandhan-bank.png', color: '#dc3729', accent: '#093252' },
  'bank-of-baroda': { logo: '/banks/bank-of-baroda.png', color: '#ea5e0f', accent: null },
  'bank-of-india': { logo: '/banks/bank-of-india.png', color: '#d56f39', accent: null },
  'bank-of-maharashtra': { logo: '/banks/bank-of-maharashtra.png', color: '#73bde0', accent: null },
  'canara-bank': { logo: '/banks/canara-bank.png', color: '#019eec', accent: '#fdb500' },
  'central-bank-of-india': { logo: '/banks/central-bank-of-india.png', color: '#2276c4', accent: '#db4265' },
  'citibank': { logo: '/banks/citibank.png', color: '#056daf', accent: '#d9232a' },
  'city-union-bank': { logo: '/banks/city-union-bank.png', color: '#ed0677', accent: '#2f3295' },
  'cosmos-co-operative-bank': { logo: '/banks/cosmos-co-operative-bank.png', color: '#0098da', accent: null },
  'dbs-bank': { logo: '/banks/dbs-bank.svg', color: '#ff3333', accent: null },
  'dcb-bank': { logo: '/banks/dcb-bank.svg', color: '#2e59a8', accent: null },
  'deutsche-bank': { logo: '/banks/deutsche-bank.png', color: '#0018a8', accent: null },
  'dhanlaxmi-bank': { logo: '/banks/dhanlaxmi-bank.png', color: '#580c5e', accent: null },
  'equitas-small-finance-bank': { logo: '/banks/equitas-small-finance-bank.png', color: '#1c458a', accent: '#55b648' },
  'fino-payments-bank': { logo: '/banks/fino-payments-bank.svg', color: '#48337e', accent: '#c42521' },
  'hdfc-bank': { logo: '/banks/hdfc-bank.svg', color: '#004c8f', accent: '#ed232a' },
  'hsbc': { logo: '/banks/hsbc.png', color: '#eb3423', accent: null },
  'icici-bank': { logo: '/banks/icici-bank.svg', color: '#ef7f1a', accent: null },
  'idbi-bank': { logo: '/banks/idbi-bank.svg', color: '#f58220', accent: '#00836c' },
  'idfc-first-bank': { logo: '/banks/idfc-first-bank.svg', color: '#9d1d27', accent: null },
  'india-post-payments-bank': { logo: '/banks/india-post-payments-bank.png', color: '#c8242c', accent: '#e99a12' },
  'indian-overseas-bank': { logo: '/banks/indian-overseas-bank.png', color: '#0000fd', accent: null },
  'indusind-bank': { logo: '/banks/indusind-bank.png', color: '#9c3b3c', accent: null },
  'jammu-and-kashmir-bank': { logo: '/banks/jammu-and-kashmir-bank.png', color: '#0097d7', accent: '#9dcc49' },
  'jana-small-finance-bank': { logo: '/banks/jana-small-finance-bank.png', color: '#de3f94', accent: null },
  'karnataka-bank': { logo: '/banks/karnataka-bank.svg', color: '#92278f', accent: null },
  'karur-vysya-bank': { logo: '/banks/karur-vysya-bank.png', color: '#e7e514', accent: '#01824b' },
  'kotak-mahindra-bank': { logo: '/banks/kotak-mahindra-bank.svg', color: '#ec1c24', accent: '#003974' },
  'nkgsb-co-operative-bank': { logo: '/banks/nkgsb-co-operative-bank.png', color: '#bd4458', accent: '#6673b3' },
  'paytm-payments-bank': { logo: '/banks/paytm-payments-bank.png', color: '#002a65', accent: null },
  'punjab-and-sind-bank': { logo: '/banks/punjab-and-sind-bank.png', color: '#0e5b38', accent: '#f5e70c' },
  'punjab-national-bank': { logo: '/banks/punjab-national-bank.png', color: '#9e1b45', accent: '#fbbc35' },
  'rbl-bank': { logo: '/banks/rbl-bank.png', color: '#3d4c8d', accent: '#f0474c' },
  'saraswat-co-operative-bank': { logo: '/banks/saraswat-co-operative-bank.png', color: '#d2303f', accent: '#f6af3a' },
  'south-indian-bank': { logo: '/banks/south-indian-bank.png', color: '#d3252e', accent: null },
  'standard-chartered-bank': { logo: '/banks/standard-chartered-bank.png', color: '#0473ea', accent: '#38d200' },
  'state-bank-of-india': { logo: '/banks/state-bank-of-india.png', color: '#0199cc', accent: null },
  'svc-co-operative-bank': { logo: '/banks/svc-co-operative-bank.png', color: '#0088ce', accent: null },
  'tamilnad-mercantile-bank': { logo: '/banks/tamilnad-mercantile-bank.svg', color: '#2e4291', accent: '#c81d82' },
  'tjsb-sahakari-bank': { logo: '/banks/tjsb-sahakari-bank.png', color: '#c52529', accent: null },
  'uco-bank': { logo: '/banks/uco-bank.png', color: '#2070d2', accent: null },
  'ujjivan-small-finance-bank': { logo: '/banks/ujjivan-small-finance-bank.svg', color: '#fec040', accent: '#229e82' },
  'union-bank-of-india': { logo: '/banks/union-bank-of-india.png', color: '#174996', accent: '#ea1c24' },
  'yes-bank': { logo: '/banks/yes-bank.png', color: '#e91e47', accent: null },
};
