/**
 * Bank logos and brand colours, keyed by `bankSlug()` of the display name.
 *
 * GENERATED by `scripts/fetch-bank-logos.py` — do not edit by hand; add a
 * COLOR_OVERRIDES / REJECT_URLS entry in the script instead.
 *
 * Logos are each bank's own image, fetched from its own domain and
 * committed rather than hot-linked. Colours are measured from the logo
 * pixels (dominant saturated hue + a second distinct hue when present).
 * `aspect` is the trimmed mark's width / height, so the UI can size a
 * plate to a wordmark instead of shrinking it into a square.
 * A bank missing here renders initials and a neutral tile — a guessed
 * logo or colour would be worse.
 */
export interface BankBrandAsset {
  logo: string | null;
  color: string | null;
  accent: string | null;
  aspect: number;
}

export const BANK_BRAND_ASSETS: Readonly<Record<string, BankBrandAsset>> = {
  'airtel-payments-bank': { logo: '/banks/airtel-payments-bank.png', color: '#ed1b24', accent: null, aspect: 1.033 },
  'au-small-finance-bank': { logo: '/banks/au-small-finance-bank.png', color: '#eb691f', accent: '#6d276d', aspect: 1 },
  'axis-bank': { logo: '/banks/axis-bank.png', color: '#97144d', accent: null, aspect: 1.231 },
  'bandhan-bank': { logo: '/banks/bandhan-bank.png', color: '#093252', accent: '#dc3729', aspect: 3.345 },
  'bank-of-baroda': { logo: '/banks/bank-of-baroda.png', color: '#ea5e0f', accent: null, aspect: 1 },
  'bank-of-india': { logo: '/banks/bank-of-india.png', color: '#de6f34', accent: null, aspect: 0.875 },
  'bank-of-maharashtra': { logo: '/banks/bank-of-maharashtra.png', color: '#73bde0', accent: null, aspect: 1 },
  'canara-bank': { logo: '/banks/canara-bank.png', color: '#019fec', accent: '#ffb601', aspect: 1.258 },
  'central-bank-of-india': { logo: '/banks/central-bank-of-india.png', color: '#1c73c2', accent: '#d01a4c', aspect: 3.231 },
  'citibank': { logo: '/banks/citibank.png', color: '#056daf', accent: '#d9232a', aspect: 1.688 },
  'city-union-bank': { logo: '/banks/city-union-bank.png', color: '#ee0678', accent: '#303399', aspect: 1.078 },
  'cosmos-co-operative-bank': { logo: '/banks/cosmos-co-operative-bank.png', color: '#0098db', accent: null, aspect: 0.648 },
  'dbs-bank': { logo: '/banks/dbs-bank.svg', color: '#ff3333', accent: null, aspect: 3.357 },
  'dcb-bank': { logo: '/banks/dcb-bank.svg', color: '#2e59a8', accent: null, aspect: 4.111 },
  'deutsche-bank': { logo: '/banks/deutsche-bank.png', color: '#0018a8', accent: null, aspect: 1 },
  'dhanlaxmi-bank': { logo: '/banks/dhanlaxmi-bank.png', color: '#580c5e', accent: null, aspect: 1 },
  'equitas-small-finance-bank': { logo: '/banks/equitas-small-finance-bank.png', color: '#1c458a', accent: '#56b848', aspect: 1 },
  'fino-payments-bank': { logo: '/banks/fino-payments-bank.svg', color: '#48337e', accent: '#c42521', aspect: 6.75 },
  'hdfc-bank': { logo: '/banks/hdfc-bank.svg', color: '#004c8f', accent: '#ed232a', aspect: 5.086 },
  'hsbc': { logo: '/banks/hsbc.png', color: '#ec3423', accent: null, aspect: 2 },
  'icici-bank': { logo: '/banks/icici-bank.svg', color: '#ef7f1a', accent: null, aspect: 4.844 },
  'idbi-bank': { logo: '/banks/idbi-bank.svg', color: '#f58220', accent: '#00836c', aspect: 4.812 },
  'idfc-first-bank': { logo: '/banks/idfc-first-bank.svg', color: '#9d1d27', accent: null, aspect: 2.831 },
  'india-post-payments-bank': { logo: '/banks/india-post-payments-bank.png', color: '#c8252c', accent: '#fee201', aspect: 4.282 },
  'indian-overseas-bank': { logo: '/banks/indian-overseas-bank.png', color: '#0000ff', accent: null, aspect: 1.028 },
  'indusind-bank': { logo: '/banks/indusind-bank.png', color: '#9c3b3c', accent: null, aspect: 1 },
  'jammu-and-kashmir-bank': { logo: '/banks/jammu-and-kashmir-bank.png', color: '#0096d7', accent: '#9dcc49', aspect: 2.708 },
  'jana-small-finance-bank': { logo: '/banks/jana-small-finance-bank.png', color: '#dc2e8c', accent: null, aspect: 2.708 },
  'karnataka-bank': { logo: '/banks/karnataka-bank.svg', color: '#92278f', accent: null, aspect: 1 },
  'karur-vysya-bank': { logo: '/banks/karur-vysya-bank.png', color: '#e7e414', accent: '#01824b', aspect: 1.008 },
  'kotak-mahindra-bank': { logo: '/banks/kotak-mahindra-bank.svg', color: '#ec1c24', accent: '#003974', aspect: 3.69 },
  'nkgsb-co-operative-bank': { logo: '/banks/nkgsb-co-operative-bank.png', color: '#bc4358', accent: '#6673b3', aspect: 0.945 },
  'paytm-payments-bank': { logo: '/banks/paytm-payments-bank.png', color: '#002e6e', accent: null, aspect: 0.875 },
  'punjab-and-sind-bank': { logo: '/banks/punjab-and-sind-bank.png', color: '#105c39', accent: '#f7eb0d', aspect: 6.857 },
  'punjab-national-bank': { logo: '/banks/punjab-national-bank.png', color: '#9e1b45', accent: '#fbbc35', aspect: 1 },
  'rbl-bank': { logo: '/banks/rbl-bank.png', color: '#3b4a8c', accent: '#ef484d', aspect: 2.408 },
  'saraswat-co-operative-bank': { logo: '/banks/saraswat-co-operative-bank.png', color: '#d63142', accent: null, aspect: 3.339 },
  'south-indian-bank': { logo: '/banks/south-indian-bank.png', color: '#d0242d', accent: null, aspect: 2.487 },
  'standard-chartered-bank': { logo: '/banks/standard-chartered-bank.png', color: '#0473eb', accent: '#38d200', aspect: 0.641 },
  'state-bank-of-india': { logo: '/banks/state-bank-of-india.png', color: '#0199cc', accent: null, aspect: 1 },
  'svc-co-operative-bank': { logo: '/banks/svc-co-operative-bank.png', color: '#0083c9', accent: null, aspect: 4.054 },
  'tamilnad-mercantile-bank': { logo: '/banks/tamilnad-mercantile-bank.svg', color: '#2e4291', accent: '#c81d82', aspect: 3.225 },
  'tjsb-sahakari-bank': { logo: '/banks/tjsb-sahakari-bank.png', color: '#c5262a', accent: null, aspect: 2.692 },
  'uco-bank': { logo: '/banks/uco-bank.png', color: '#2071d2', accent: null, aspect: 1 },
  'ujjivan-small-finance-bank': { logo: '/banks/ujjivan-small-finance-bank.svg', color: '#fec040', accent: '#229e82', aspect: 7.937 },
  'union-bank-of-india': { logo: '/banks/union-bank-of-india.png', color: '#174996', accent: '#ea1c24', aspect: 6.696 },
  'yes-bank': { logo: '/banks/yes-bank.png', color: '#ed1f48', accent: null, aspect: 1.143 },
};
