/**
 * Official card-face artwork, keyed by catalog id and the network printed on
 * the face. See data/creditCardCatalog for the ids.
 *
 * GENERATED by `scripts/fetch-card-art.py` — do not edit by hand; add a
 * SOURCES entry in the script instead. Every face is the issuer's own image,
 * committed rather than hot-linked, and was checked by eye on the contact sheet.
 */
import type { CardNetwork } from '@/data/creditCardCatalog';

export interface CardArt {
  /** Public path of the face image. */
  src: string;
  /** The card stands upright (portrait). */
  vertical: boolean;
}

/** `ANY`: the face prints no network mark, so it fits the product on any network. */
export const CARD_ART: Readonly<Record<string, Partial<Record<CardNetwork | 'ANY', CardArt>>>> = {
  'amex-gold': { AMEX: { src: '/cards/amex-gold--amex.webp', vertical: false } },
  'amex-mrcc': { AMEX: { src: '/cards/amex-mrcc--amex.webp', vertical: false } },
  'amex-platinum': { AMEX: { src: '/cards/amex-platinum--amex.webp', vertical: false } },
  'amex-platinum-reserve': { AMEX: { src: '/cards/amex-platinum-reserve--amex.webp', vertical: false } },
  'amex-platinum-travel': { AMEX: { src: '/cards/amex-platinum-travel--amex.webp', vertical: false } },
  'amex-smartearn': { AMEX: { src: '/cards/amex-smartearn--amex.webp', vertical: false } },
  'au-zenith-plus': { ANY: { src: '/cards/au-zenith-plus--any.webp', vertical: true } },
  'axis-ace': { ANY: { src: '/cards/axis-ace--any.webp', vertical: false } },
  'axis-airtel': { ANY: { src: '/cards/axis-airtel--any.webp', vertical: false } },
  'axis-atlas': { ANY: { src: '/cards/axis-atlas--any.webp', vertical: false } },
  'axis-flipkart': { MASTERCARD: { src: '/cards/axis-flipkart--mastercard.webp', vertical: false } },
  'axis-horizon': { ANY: { src: '/cards/axis-horizon--any.webp', vertical: false } },
  'axis-myzone': { ANY: { src: '/cards/axis-myzone--any.webp', vertical: false } },
  'axis-neo': { ANY: { src: '/cards/axis-neo--any.webp', vertical: false } },
  'axis-privilege': { ANY: { src: '/cards/axis-privilege--any.webp', vertical: false } },
  'axis-reserve': { ANY: { src: '/cards/axis-reserve--any.webp', vertical: true } },
  'axis-samsung': { ANY: { src: '/cards/axis-samsung--any.webp', vertical: false } },
  'axis-select': { ANY: { src: '/cards/axis-select--any.webp', vertical: false } },
  'bob-eterna': { ANY: { src: '/cards/bob-eterna--any.webp', vertical: false } },
  'bob-onecard': { ANY: { src: '/cards/bob-onecard--any.webp', vertical: true } },
  'federal-celesta': { VISA: { src: '/cards/federal-celesta--visa.webp', vertical: true } },
  'federal-scapia': { RUPAY: { src: '/cards/federal-scapia--rupay.webp', vertical: true }, VISA: { src: '/cards/federal-scapia--visa.webp', vertical: true } },
  'federal-signet': { VISA: { src: '/cards/federal-signet--visa.webp', vertical: false } },
  'hdfc-diners-black': { DINERS: { src: '/cards/hdfc-diners-black--diners.webp', vertical: false } },
  'hdfc-diners-black-metal': { DINERS: { src: '/cards/hdfc-diners-black-metal--diners.webp', vertical: false } },
  'hdfc-diners-privilege': { DINERS: { src: '/cards/hdfc-diners-privilege--diners.webp', vertical: false } },
  'hdfc-freedom': { ANY: { src: '/cards/hdfc-freedom--any.webp', vertical: false } },
  'hdfc-indianoil': { ANY: { src: '/cards/hdfc-indianoil--any.webp', vertical: false } },
  'hdfc-infinia': { MASTERCARD: { src: '/cards/hdfc-infinia--mastercard.webp', vertical: false } },
  'hdfc-marriott-bonvoy': { ANY: { src: '/cards/hdfc-marriott-bonvoy--any.webp', vertical: false } },
  'hdfc-millennia': { ANY: { src: '/cards/hdfc-millennia--any.webp', vertical: false } },
  'hdfc-moneyback-plus': { ANY: { src: '/cards/hdfc-moneyback-plus--any.webp', vertical: false } },
  'hdfc-regalia-gold': { ANY: { src: '/cards/hdfc-regalia-gold--any.webp', vertical: false } },
  'hdfc-shoppers-stop': { ANY: { src: '/cards/hdfc-shoppers-stop--any.webp', vertical: false } },
  'hdfc-swiggy': { ANY: { src: '/cards/hdfc-swiggy--any.webp', vertical: false } },
  'hdfc-tata-neu-infinity': { ANY: { src: '/cards/hdfc-tata-neu-infinity--any.webp', vertical: true } },
  'hdfc-tata-neu-plus': { ANY: { src: '/cards/hdfc-tata-neu-plus--any.webp', vertical: true } },
  'hsbc-premier': { MASTERCARD: { src: '/cards/hsbc-premier--mastercard.webp', vertical: true } },
  'hsbc-travelone': { MASTERCARD: { src: '/cards/hsbc-travelone--mastercard.webp', vertical: true } },
  'icici-amazon-pay': { VISA: { src: '/cards/icici-amazon-pay--visa.webp', vertical: false } },
  'icici-coral': { ANY: { src: '/cards/icici-coral--any.webp', vertical: false } },
  'icici-emeralde': { ANY: { src: '/cards/icici-emeralde--any.webp', vertical: false } },
  'icici-emeralde-private': { ANY: { src: '/cards/icici-emeralde-private--any.webp', vertical: false } },
  'icici-hpcl': { ANY: { src: '/cards/icici-hpcl--any.webp', vertical: true } },
  'icici-makemytrip': { ANY: { src: '/cards/icici-makemytrip--any.webp', vertical: false } },
  'icici-rubyx': { ANY: { src: '/cards/icici-rubyx--any.webp', vertical: false } },
  'icici-sapphiro': { ANY: { src: '/cards/icici-sapphiro--any.webp', vertical: false } },
  'icici-times-black': { ANY: { src: '/cards/icici-times-black--any.webp', vertical: false } },
  'idfc-ashva': { ANY: { src: '/cards/idfc-ashva--any.webp', vertical: false } },
  'idfc-classic': { ANY: { src: '/cards/idfc-classic--any.webp', vertical: false } },
  'idfc-first-private': { VISA: { src: '/cards/idfc-first-private--visa.webp', vertical: false } },
  'idfc-mayura': { ANY: { src: '/cards/idfc-mayura--any.webp', vertical: false } },
  'idfc-millennia': { VISA: { src: '/cards/idfc-millennia--visa.webp', vertical: true } },
  'idfc-select': { ANY: { src: '/cards/idfc-select--any.webp', vertical: false } },
  'idfc-wealth': { ANY: { src: '/cards/idfc-wealth--any.webp', vertical: false } },
  'idfc-wow': { VISA: { src: '/cards/idfc-wow--visa.webp', vertical: false } },
  'indusind-eazydiner': { VISA: { src: '/cards/indusind-eazydiner--visa.webp', vertical: false } },
  'indusind-legend': { ANY: { src: '/cards/indusind-legend--any.webp', vertical: false } },
  'indusind-pinnacle': { ANY: { src: '/cards/indusind-pinnacle--any.webp', vertical: true } },
  'indusind-tiger': { VISA: { src: '/cards/indusind-tiger--visa.webp', vertical: true } },
  'kotak-indigo': { ANY: { src: '/cards/kotak-indigo--any.webp', vertical: true } },
  'kotak-league': { ANY: { src: '/cards/kotak-league--any.webp', vertical: false } },
  'kotak-zen': { ANY: { src: '/cards/kotak-zen--any.webp', vertical: false } },
  'rbl-icon': { ANY: { src: '/cards/rbl-icon--any.webp', vertical: false } },
  'rbl-world-safari': { ANY: { src: '/cards/rbl-world-safari--any.webp', vertical: false } },
  'sbi-aurum': { ANY: { src: '/cards/sbi-aurum--any.webp', vertical: false } },
  'sbi-bpcl': { ANY: { src: '/cards/sbi-bpcl--any.webp', vertical: false } },
  'sbi-bpcl-octane': { ANY: { src: '/cards/sbi-bpcl-octane--any.webp', vertical: false } },
  'sbi-cashback': { ANY: { src: '/cards/sbi-cashback--any.webp', vertical: true } },
  'sbi-elite': { ANY: { src: '/cards/sbi-elite--any.webp', vertical: false } },
  'sbi-irctc': { ANY: { src: '/cards/sbi-irctc--any.webp', vertical: false } },
  'sbi-miles-elite': { ANY: { src: '/cards/sbi-miles-elite--any.webp', vertical: true } },
  'sbi-paytm': { ANY: { src: '/cards/sbi-paytm--any.webp', vertical: false } },
  'sbi-prime': { ANY: { src: '/cards/sbi-prime--any.webp', vertical: false } },
  'sbi-pulse': { ANY: { src: '/cards/sbi-pulse--any.webp', vertical: false } },
  'sbi-simplyclick': { ANY: { src: '/cards/sbi-simplyclick--any.webp', vertical: true } },
  'sbi-simplysave': { ANY: { src: '/cards/sbi-simplysave--any.webp', vertical: true } },
};
