/**
 * Official card-face artwork, keyed by catalog id and the network printed on
 * the face. See data/creditCardCatalog for the ids.
 *
 * GENERATED by `scripts/fetch-card-art.py` — do not edit by hand; add a
 * SOURCES entry in the script instead. Every face is the issuer's own image,
 * committed rather than hot-linked, and was checked by eye on the contact sheet.
 */
import type { CardNetwork } from '@/data/creditCardCatalog';

export interface CardArt {
  /** Public path of the face image. */
  src: string;
  /** The card stands upright (portrait). */
  vertical: boolean;
}

export const CARD_ART: Readonly<Record<string, Partial<Record<CardNetwork, CardArt>>>> = {
  'federal-scapia': { RUPAY: { src: '/cards/federal-scapia--rupay.webp', vertical: true }, VISA: { src: '/cards/federal-scapia--visa.webp', vertical: true } },
};
