/**
 * Insurer logos and brand colours, keyed by `insurerSlug()` of the name.
 *
 * GENERATED by `scripts/fetch-insurer-logos.py` — do not edit by hand; add a
 * COLOR_OVERRIDES / REJECT_URLS entry in the script instead.
 *
 * Logos are each insurer's own image, fetched from its own domain and
 * committed rather than hot-linked. Colours are measured from the logo
 * pixels. An insurer missing here renders initials on its kind-of-cover
 * colour — a guessed logo or colour would be worse.
 */
export interface InsurerBrandAsset {
  logo: string | null;
  color: string | null;
  accent: string | null;
  aspect: number;
}

export const INSURER_BRAND_ASSETS: Readonly<Record<string, InsurerBrandAsset>> = {
  'acko': { logo: '/insurers/acko.png', color: '#7d48e1', accent: null, aspect: 1 },
  'aditya-birla-health': { logo: '/insurers/aditya-birla-health.png', color: '#c8222a', accent: null, aspect: 1 },
  'aditya-birla-sun-life-insurance': { logo: '/insurers/aditya-birla-sun-life-insurance.png', color: '#c22b3f', accent: '#f4b84f', aspect: 2.539 },
  'ageas-federal-life': { logo: '/insurers/ageas-federal-life.svg', color: '#7610bf', accent: '#f26f21', aspect: 3.05 },
  'aviva-life': { logo: '/insurers/aviva-life.png', color: '#024fb6', accent: null, aspect: 5.731 },
  'axis-max-life': { logo: '/insurers/axis-max-life.png', color: '#9a2051', accent: '#28467a', aspect: 3.623 },
  'bajaj-allianz-general': { logo: '/insurers/bajaj-allianz-general.png', color: '#0460ad', accent: null, aspect: 2.789 },
  'bajaj-allianz-life': { logo: '/insurers/bajaj-allianz-life.png', color: '#0561ae', accent: null, aspect: 1 },
  'bandhan-life': { logo: '/insurers/bandhan-life.png', color: '#d02716', accent: '#235aa3', aspect: 1 },
  'canara-hsbc-life': { logo: '/insurers/canara-hsbc-life.png', color: '#d32933', accent: '#2395cb', aspect: 3.336 },
  'care-health-insurance': { logo: '/insurers/care-health-insurance.png', color: '#fedf01', accent: null, aspect: 1 },
  'cholamandalam-ms': { logo: '/insurers/cholamandalam-ms.png', color: '#e41936', accent: '#18398b', aspect: 4.385 },
  'edelweiss-life': { logo: '/insurers/edelweiss-life.png', color: '#0c4fa4', accent: '#f99622', aspect: 4.364 },
  'go-digit': { logo: '/insurers/go-digit.png', color: '#f2b206', accent: null, aspect: 1 },
  'hdfc-ergo': { logo: '/insurers/hdfc-ergo.png', color: '#d9232c', accent: null, aspect: 1 },
  'hdfc-life': { logo: '/insurers/hdfc-life.png', color: '#e2101a', accent: null, aspect: 1 },
  'icici-lombard': { logo: '/insurers/icici-lombard.png', color: '#b12f34', accent: null, aspect: 0.917 },
  'icici-prudential-life': { logo: '/insurers/icici-prudential-life.png', color: '#b02b32', accent: null, aspect: 0.923 },
  'iffco-tokio': { logo: '/insurers/iffco-tokio.png', color: '#0ca3e5', accent: '#0aa856', aspect: 1 },
  'indiafirst-life': { logo: '/insurers/indiafirst-life.png', color: '#f26724', accent: '#0394d3', aspect: 1.773 },
  'kotak-life': { logo: '/insurers/kotak-life.png', color: '#1e4679', accent: null, aspect: 1.143 },
  'lic': { logo: '/insurers/lic.png', color: '#fccb09', accent: '#07569e', aspect: 2.062 },
  'magma-general': { logo: '/insurers/magma-general.png', color: '#e00512', accent: null, aspect: 1 },
  'manipalcigna': { logo: '/insurers/manipalcigna.png', color: '#e9652b', accent: '#1c84c5', aspect: 4.987 },
  'national-insurance': { logo: '/insurers/national-insurance.svg', color: '#2c2b7c', accent: '#00989f', aspect: 2.095 },
  'navi-general': { logo: '/insurers/navi-general.svg', color: '#3c0050', accent: '#22d081', aspect: 2.7 },
  'new-india-assurance': { logo: '/insurers/new-india-assurance.png', color: '#30497f', accent: null, aspect: 1 },
  'niva-bupa': { logo: '/insurers/niva-bupa.png', color: '#05b0f0', accent: null, aspect: 0.953 },
  'oriental-insurance': { logo: '/insurers/oriental-insurance.png', color: '#494b97', accent: null, aspect: 1 },
  'pnb-metlife': { logo: '/insurers/pnb-metlife.svg', color: '#efbb1b', accent: '#15335a', aspect: 3.409 },
  'pramerica-life': { logo: '/insurers/pramerica-life.svg', color: '#007bc3', accent: null, aspect: 3.568 },
  'reliance-general': { logo: '/insurers/reliance-general.png', color: '#9b282b', accent: '#002e80', aspect: 3.048 },
  'sbi-general': { logo: '/insurers/sbi-general.png', color: '#671d6c', accent: '#272e61', aspect: 3.444 },
  'sbi-life': { logo: '/insurers/sbi-life.svg', color: '#302a6f', accent: null, aspect: 4.914 },
  'shriram-life': { logo: '/insurers/shriram-life.svg', color: '#007dcd', accent: null, aspect: 2.237 },
  'star-health': { logo: '/insurers/star-health.png', color: '#506099', accent: null, aspect: 1 },
  'star-union-dai-ichi-life': { logo: '/insurers/star-union-dai-ichi-life.png', color: '#f15339', accent: '#1881c2', aspect: 1.091 },
  'tata-aia-life': { logo: '/insurers/tata-aia-life.svg', color: '#b67e27', accent: '#d62049', aspect: 4.536 },
  'tata-aig': { logo: '/insurers/tata-aig.svg', color: '#005baa', accent: null, aspect: 2.133 },
  'united-india-insurance': { logo: '/insurers/united-india-insurance.png', color: '#fcdd0b', accent: '#1a519e', aspect: 1.316 },
  'zuno-general': { logo: '/insurers/zuno-general.png', color: '#1ab2ac', accent: null, aspect: 1 },
};
