-- Foreign exchanges for FOREIGN_EQUITY support.
ALTER TYPE "Exchange" ADD VALUE IF NOT EXISTS 'NASDAQ';
ALTER TYPE "Exchange" ADD VALUE IF NOT EXISTS 'NYSE';
ALTER TYPE "Exchange" ADD VALUE IF NOT EXISTS 'LSE';
ALTER TYPE "Exchange" ADD VALUE IF NOT EXISTS 'HKEX';
ALTER TYPE "Exchange" ADD VALUE IF NOT EXISTS 'SGX';
ALTER TYPE "Exchange" ADD VALUE IF NOT EXISTS 'TSE';
