#!/usr/bin/env python3
"""Normalise fetched AMC icons to one size and format, then regenerate the manifest.

Run after `scripts/fetch-amc-logos.sh`.

WHY THIS STEP EXISTS
--------------------
The icons arrive in whatever each AMC happens to publish: one was a 308KB
multi-resolution .ico holding eight frames, several were 16px PNGs, one was a
59KB SVG. Left alone that is ~1MB of assets in wildly different formats, and the
UI would need per-file knowledge of which extension to ask for.

One format at one size removes both problems. The largest frame in an .ico is
the one kept — the small frames are the same mark at a resolution too low for a
40px avatar on a retina screen.

SVGs are left alone. They are already resolution-independent and rasterising one
to 128px would throw that away.

ASPECT RATIO IS PRESERVED
-------------------------
These marks are roundels, squares and wide wordmarks. Each is fitted inside a
transparent square rather than stretched to fill it: squashing a wordmark into a
square is how a logo stops looking like itself.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit('needs Pillow:  pip install Pillow')

SIZE = 128
ROOT = Path(__file__).resolve().parent.parent
LOGO_DIR = ROOT / 'apps/web/public/amc'
MANIFEST = ROOT / 'apps/web/src/lib/amcLogos.ts'


def amc_slug(name: str) -> str:
    """Mirror of `amcSlug()` in apps/web/src/components/mf/AmcLogo.tsx."""
    s = re.sub(r'\bmutual\s+fund\b', ' ', name, flags=re.I)
    return re.sub(r'[^A-Za-z0-9]+', '-', s).strip('-').lower()


def normalise(path: Path) -> Path:
    if path.suffix.lower() == '.svg':
        return path
    im = Image.open(path)
    if getattr(im, 'format', '') == 'ICO':
        im = im.ico.getimage(max(im.ico.sizes()))
    im = im.convert('RGBA')
    im.thumbnail((SIZE, SIZE), Image.LANCZOS)
    canvas = Image.new('RGBA', (SIZE, SIZE), (0, 0, 0, 0))
    canvas.paste(im, ((SIZE - im.width) // 2, (SIZE - im.height) // 2), im)
    out = path.with_suffix('.png')
    canvas.save(out, 'PNG', optimize=True)
    if out != path:
        path.unlink()
    return out


def main() -> None:
    before = after = 0
    for path in sorted(LOGO_DIR.iterdir()):
        if not path.is_file():
            continue
        before += path.stat().st_size
        try:
            out = normalise(path)
        except Exception as exc:  # noqa: BLE001 — one bad file must not stop the rest
            print(f'  SKIP  {path.name}: {exc}')
            continue
        after += out.stat().st_size
    print(f'{before} -> {after} bytes')

    files = {p.stem: p.name for p in sorted(LOGO_DIR.iterdir()) if p.is_file()}

    # The AMC names to key on. Passed in (one per line on stdin) when regenerating
    # against a live database; otherwise the existing filenames are trusted, which
    # keeps the manifest stable for anyone without a database to hand.
    names = [ln.strip() for ln in sys.stdin] if not sys.stdin.isatty() else []
    entries = (
        sorted({(amc_slug(n), n) for n in names if amc_slug(n) in files})
        if names
        else sorted((slug, '') for slug in files)
    )
    missing = sorted({n for n in names if amc_slug(n) not in files})
    for n in missing:
        print(f'  NO LOGO  {n}')

    lines = [
        '/**',
        ' * AMC logo files, keyed by the slug `amcSlug()` derives from an AMC name.',
        ' *',
        ' * GENERATED by `scripts/normalise-amc-logos.py` — do not edit by hand.',
        ' *',
        " * Each file is that fund house's own mark, fetched from its own site and",
        ' * committed here rather than hot-linked. An <img> pointed at a third-party',
        " * logo service would put a request to someone else's server on every fund",
        ' * page a reader opens, telling that service which funds this person is',
        ' * researching, and would break the page when the service ends its free tier.',
        ' *',
        ' * An AMC absent from this map is not a bug — it renders the monogram, which',
        ' * is the honest fallback. A wrong logo would be worse than initials.',
        ' */',
        'export const AMC_LOGOS: Readonly<Record<string, string>> = {',
    ]
    for slug, name in entries:
        comment = f'  // {name}' if name else ''
        lines.append(f"  '{slug}': '/amc/{files[slug]}',{comment}")
    lines += ['};', '']
    MANIFEST.write_text('\n'.join(lines), encoding='utf-8', newline='\n')
    print(f'wrote {MANIFEST.relative_to(ROOT)} with {len(entries)} logos')


if __name__ == '__main__':
    main()
