/**
 * Short explanations for every chart, card and metric on the Analytics page,
 * shown behind the "i" button next to each title.
 *
 * Kept in one place so the wording can be reviewed and edited without
 * touching the widgets. Each entry describes what the number ACTUALLY is, as
 * computed in packages/api/src/services/analytics.service.ts and
 * analytics.risk.ts — including where that differs from what the title might
 * suggest (the benchmark line includes money you add; the weight grid is not
 * a return correlation; "inflow" means cash coming back to you). Keep them in
 * step if those calculations change.
 *
 * Time frames matter here: only some cards follow the period selector. The
 * rest are "as of today" or "this financial year" (April–March), and each
 * explanation says which.
 */

export interface InfoCopy {
  title: string;
  body: string[];
}

const PERIOD = 'Follows the period selected at the top.';
const FY = 'This financial year (April–March).';

export const ANALYTICS_INFO = {
  // ── KPI cards ───────────────────────────────────────────────────────
  currentValue: {
    title: 'Current value',
    body: [
      'What your holdings are worth today at the latest available prices.',
      '"Invested" is what you paid for the holdings you still own.',
    ],
  },
  unrealisedPnl: {
    title: 'Unrealised P&L',
    body: [
      'Gain or loss on holdings you still own: current value minus what you paid. It only becomes real when you sell.',
      'The % is measured against the amount invested.',
    ],
  },
  xirrOverall: {
    title: 'XIRR overall',
    body: [
      'Your annualised return, taking into account when each rupee went in or came out — so money added recently isn’t treated as if it had been invested from the start.',
      'Shown after about 90 days of history; annualising a shorter period gives misleading numbers. 1Y / 3Y / 5Y are the same measure over those windows.',
    ],
  },
  realisedPnlFy: {
    title: 'Realised P&L (FY)',
    body: [
      `Profit or loss locked in by selling investments: sale value minus what you paid. ${FY}`,
      'This is the book figure. The tax-harvesting card below shows the taxable figure, which can differ where grandfathering or indexation applies.',
    ],
  },
  incomeFy: {
    title: 'Income (FY)',
    body: [
      'Dividends, interest and maturity payouts received, plus interest accrued on fixed deposits, NSC, RD and post-office schemes.',
      FY,
    ],
  },
  totalReturns: {
    title: 'Total returns',
    body: [
      'Unrealised P&L on what you hold today plus realised P&L from sales this financial year.',
      'It combines two different time frames, so it isn’t your lifetime return — XIRR is the better measure of that.',
    ],
  },

  // ── AI ──────────────────────────────────────────────────────────────
  insights: {
    title: 'AI portfolio insights',
    body: [
      'Observations generated by AI from your portfolio data for the selected portfolio and period, covering diversification, tax optimisation, underperformers, idle cash, sector tilt and concentration risk.',
      'A starting point for your own review, not financial advice.',
    ],
  },

  // ── Performance ─────────────────────────────────────────────────────
  valueOverTime: {
    title: 'Portfolio value over time',
    body: [
      'The solid line is the market value of your holdings; the dashed line is the amount you had invested in them at each point. The gap between them is your gain or loss.',
      PERIOD,
    ],
  },
  returnOnCapital: {
    title: 'Return on invested capital',
    body: [
      'How far your portfolio’s market value is above or below what you invested, as a percentage, at each point in time: (value − invested) ÷ invested.',
      PERIOD,
    ],
  },
  benchmark: {
    title: 'Portfolio vs NIFTY 50 / Sensex',
    body: [
      'Your portfolio and the two indices, each rescaled to start at 100 so their paths can be compared on one chart.',
      'Your line tracks total value, so money you add or withdraw moves it as well — treat it as a rough comparison, not a pure returns race.',
      PERIOD,
    ],
  },
  assetsVsLiabilities: {
    title: 'Assets vs liabilities',
    body: [
      'Everything you own against everything you owe. Net worth = assets − liabilities.',
      'Debt-to-asset ratio = liabilities ÷ assets. Under 30% is shown as comfortable, 30–50% as moderate and above 50% as high leverage.',
    ],
  },

  // ── Allocation ──────────────────────────────────────────────────────
  allocationByClass: {
    title: 'Allocation by class',
    body: [
      'How your money is split across asset types — stocks, mutual funds, deposits, gold and so on — based on today’s value.',
    ],
  },
  allocationByHolding: {
    title: 'Allocation by holding',
    body: [
      'Each box is one holding, sized by its current value. The biggest boxes are where most of your money sits.',
    ],
  },
  sectorAllocation: {
    title: 'Sector allocation',
    body: [
      'How the stocks you hold directly are spread across industry sectors, based on today’s value.',
      'Mutual funds, deposits, gold and other assets aren’t included. Stocks whose sector isn’t known show as Unclassified.',
    ],
  },

  // ── Returns & concentration ─────────────────────────────────────────
  concentration: {
    title: 'Concentration',
    body: [
      'Your largest holdings by current value, each as a share of the portfolio, with a running total ("cum").',
      'When a few holdings make up most of your money — above 60% is flagged — a fall in any one of them hits the whole portfolio hard.',
    ],
  },
  xirrByClass: {
    title: 'XIRR by asset class',
    body: [
      'Annualised return (XIRR) for each asset type over the whole time you’ve held it. Green is a gain, red a loss.',
      'Across several portfolios it’s an average weighted by the amount invested in each.',
    ],
  },
  realisedVsUnrealised: {
    title: 'Realised vs unrealised',
    body: [
      'Realised: profit or loss from sales this financial year. Unrealised: paper gain or loss on everything you still hold.',
      'Together they show how much of your result is already locked in and how much is still exposed to the market.',
    ],
  },
  topWinners: {
    title: 'Top 10 winners',
    body: [
      'Holdings you still own with the biggest percentage gain on what you paid.',
      'Ranked by %, not by rupees, so a small holding can top the list.',
    ],
  },
  topLosers: {
    title: 'Top 10 losers',
    body: [
      'Holdings you still own with the biggest percentage loss on what you paid.',
      'Ranked by %, not by rupees. These are also the natural candidates for tax-loss harvesting below.',
    ],
  },

  // ── Tax & cashflow ──────────────────────────────────────────────────
  cgByFy: {
    title: 'Capital gains by FY',
    body: [
      'Profit or loss from sales in each financial year, split by tax type: intraday (bought and sold the same day), short-term (STCG) and long-term (LTCG). The last six years are shown.',
    ],
  },
  incomeByMonth: {
    title: 'Income by month',
    body: [
      'Dividends, interest and maturity payouts received each month, including interest accrued on fixed deposits, NSC, RD and post-office schemes. Up to the last 12 months are shown.',
      PERIOD,
    ],
  },
  netFlow: {
    title: 'Net flow by month',
    body: [
      'Money moving between you and your investments. Inflow is cash coming back to you (sales, redemptions, dividends, interest, maturities); outflow is money you put in (buys, SIPs, deposits).',
      'A green bar is a month where you took out more than you invested; red is a month where you invested more. Up to the last 12 months are shown.',
      PERIOD,
    ],
  },

  // ── Risk ────────────────────────────────────────────────────────────
  volatility: {
    title: 'Volatility (annualised)',
    body: [
      'How much your portfolio’s value swings, annualised from its month-to-month changes. Higher means a bumpier ride.',
      'It’s based on total value, so adding or withdrawing money also shows up as a swing.',
    ],
  },
  sharpe: {
    title: 'Sharpe ratio',
    body: [
      'Return earned for each unit of risk taken, after subtracting a 6.5% risk-free rate (roughly the Indian 10-year government bond yield).',
      'Above 1 is strong, 0 to 1 is modest, and below 0 means a risk-free option would have done better.',
      'Both halves are based on total value, so money you add counts as growth and flatters the ratio. Regular SIPs can make this look strong on their own — XIRR is the honest return measure.',
    ],
  },
  maxDrawdown: {
    title: 'Max drawdown',
    body: [
      'The biggest fall from a peak to a later low in the selected period — the worst loss you would have had to sit through.',
      'It’s based on total value, so a large withdrawal can look like a drop.',
    ],
  },
  beta: {
    title: 'Beta vs NIFTY',
    body: [
      'How strongly your portfolio moves with the NIFTY 50. 1 means in step with the market, above 1 means bigger swings than the market, and below 0.5 is defensive.',
      'Needs a few months of history to calculate.',
    ],
  },
  weightGrid: {
    title: 'Asset class weight grid',
    body: [
      'Each cell shows the smaller of two asset classes’ weights; the diagonal shows each class’s own share. Darker cells mean more of your money sits in that pair.',
      'It shows where your money is concentrated, not whether those assets rise and fall together — it isn’t a return correlation.',
    ],
  },

  // ── Tax-loss harvesting ─────────────────────────────────────────────
  taxHarvest: {
    title: 'Tax-loss harvesting',
    body: [
      'Holdings currently at a loss that you could sell to book that loss and set it against capital gains this financial year, reducing your tax.',
      'These are estimates. Set-off rules and timing have conditions — check with a tax professional before acting.',
    ],
  },
  harvestLossPool: {
    title: 'Unrealised loss pool',
    body: ['The total paper loss across all holdings currently worth less than you paid.'],
  },
  harvestStcgOffset: {
    title: 'STCG offset available',
    body: [
      'Losses on holdings in the short-term bucket. Short-term losses can be set off against both short- and long-term gains.',
    ],
  },
  harvestLtcgOffset: {
    title: 'LTCG offset available',
    body: [
      'Losses on holdings in the long-term bucket. Long-term losses can only be set off against long-term gains.',
    ],
  },
  harvestRealisedFy: {
    title: 'Taxable gains (FY)',
    body: [
      `Short- and long-term gains already booked, after grandfathering and indexation — what harvested losses could offset. ${FY}`,
      'Being the taxable figure, it can differ from the book "Realised P&L (FY)" card at the top of the page.',
    ],
  },

  // ── Scenario ────────────────────────────────────────────────────────
  whatIf: {
    title: 'What-if: simulate a sale',
    body: [
      'Pick a holding and a quantity to preview a sale: proceeds, the gain or loss and whether it’s short- or long-term, estimated tax, cash left after tax, and how that holding’s share of your portfolio would change.',
      'Nothing is actually sold.',
    ],
  },
} satisfies Record<string, InfoCopy>;

export type AnalyticsInfoKey = keyof typeof ANALYTICS_INFO;
