/**
 * Short explanations for every chart, card and metric on the Analytics page,
 * shown behind the "i" button next to each title.
 *
 * Kept in one place so the wording can be reviewed and edited without
 * touching the widgets. Each entry describes what the number ACTUALLY is, as
 * computed in packages/api/src/services/analytics.service.ts and
 * analytics.risk.ts — including where that differs from what the title might
 * suggest (the benchmark line includes money you add; "inflow" means cash
 * coming back to you). Keep them in
 * step if those calculations change.
 *
 * Time frames matter here: only some cards follow the period selector. The
 * rest are "as of today" or "this financial year" (April–March), and each
 * explanation says which.
 */

export interface InfoCopy {
  title: string;
  body: string[];
}

const PERIOD = 'Follows the period selected at the top.';
const FY = 'This financial year (April–March).';

export const ANALYTICS_INFO = {
  // ── KPI cards ───────────────────────────────────────────────────────
  currentValue: {
    title: 'Current value',
    body: [
      'What your holdings are worth today at the latest available prices.',
      '"Invested" is what you paid for the holdings you still own.',
    ],
  },
  unrealisedPnl: {
    title: 'Profit if you sold today',
    body: [
      'Gain or loss on holdings you still own: current value minus what you paid. It only becomes real when you sell.',
      'The % is measured against the amount invested.',
    ],
  },
  xirrOverall: {
    title: 'Annualised return (XIRR)',
    body: [
      'Your annualised return, taking into account when each rupee went in or came out — so money added recently isn’t treated as if it had been invested from the start.',
      'Shown after about 90 days of history; annualising a shorter period gives misleading numbers. 1Y / 3Y / 5Y are the same measure over those windows.',
    ],
  },
  realisedPnlFy: {
    title: 'Realised P&L (FY)',
    body: [
      `Profit or loss locked in by selling investments: sale value minus what you paid. ${FY}`,
      'This is the book figure. The tax-harvesting card below shows the taxable figure, which can differ where grandfathering or indexation applies.',
    ],
  },
  incomeFy: {
    title: 'Income (FY)',
    body: [
      'Dividends, interest and maturity payouts received, plus interest accrued on fixed deposits, NSC, RD and post-office schemes.',
      FY,
    ],
  },

  // ── AI ──────────────────────────────────────────────────────────────
  insights: {
    title: 'AI portfolio insights',
    body: [
      'Observations generated by AI from your portfolio data for the selected portfolio and period, covering diversification, tax optimisation, underperformers, idle cash, sector tilt and concentration risk.',
      'A starting point for your own review, not financial advice.',
    ],
  },

  // ── Performance ─────────────────────────────────────────────────────
  valueOverTime: {
    title: 'Portfolio value over time',
    body: [
      'The solid line is the market value of your holdings; the dashed line is the amount you had invested in them at each point. The gap between them is your gain or loss.',
      PERIOD,
    ],
  },
  assetsVsLiabilities: {
    title: 'What you own and owe',
    body: [
      'Everything you own against everything you owe. Net worth is what is left: what you own minus what you owe.',
    ],
  },

  // ── Allocation ──────────────────────────────────────────────────────
  allocationByClass: {
    title: 'Allocation by class',
    body: [
      'How your money is split across asset types — stocks, mutual funds, deposits, gold and so on — based on today’s value.',
    ],
  },
  sectorAllocation: {
    title: 'Sector allocation',
    body: [
      'How the stocks you hold directly are spread across industry sectors, based on today’s value.',
      'Mutual funds, deposits, gold and other assets aren’t included. Stocks whose sector isn’t known show as Unclassified.',
    ],
  },

  // ── Returns & concentration ─────────────────────────────────────────
  bestAndWorst: {
    title: 'Best and worst holdings',
    body: [
      'Your biggest gains and losses in rupees, with the percentage alongside.',
      'Ranked by rupees on purpose: a small holding down 40% matters less than a large one down 5%.',
    ],
  },
  concentration: {
    title: 'Concentration',
    body: [
      'Your largest holdings by current value, each as a share of the portfolio, with a running total ("cum").',
      'When a few holdings make up most of your money — above 60% is flagged — a fall in any one of them hits the whole portfolio hard.',
    ],
  },
  xirrByClass: {
    title: 'XIRR by asset class',
    body: [
      'Annualised return (XIRR) for each asset type over the whole time you’ve held it. Green is a gain, red a loss.',
      'Across several portfolios it’s an average weighted by the amount invested in each.',
    ],
  },

  // ── Tax & cashflow ──────────────────────────────────────────────────
  cgByFy: {
    title: 'Capital gains by FY',
    body: [
      'Profit or loss from sales in each financial year, split by tax type: intraday (bought and sold the same day), short-term (STCG) and long-term (LTCG). The last six years are shown.',
    ],
  },
  incomeByMonth: {
    title: 'Income by month',
    body: [
      'Dividends, interest and maturity payouts received each month, including interest accrued on fixed deposits, NSC, RD and post-office schemes. Up to the last 12 months are shown.',
      PERIOD,
    ],
  },
  netFlow: {
    title: 'Money in and out',
    body: [
      'Money moving between you and your investments: cash coming back to you (sales, dividends, interest, maturities) against money you put in (buys, SIPs, deposits).',
      'Bars sit above the line when more came back than you put in, below it when you invested more. Neither is good or bad — investing steadily sits below. Last 12 months.',
      PERIOD,
    ],
  },

  // ── Risk ────────────────────────────────────────────────────────────
  volatility: {
    title: 'How much it swings',
    body: [
      'How much your portfolio’s value swings, annualised from its month-to-month changes. Higher means a bumpier ride.',
      'It’s based on total value, so adding or withdrawing money also shows up as a swing.',
    ],
  },
  maxDrawdown: {
    title: 'Worst fall',
    body: [
      'The biggest fall from a peak to a later low in the selected period — the worst loss you would have had to sit through.',
      'It’s based on total value, so a large withdrawal can look like a drop.',
    ],
  },
  returnCorrelation: {
    title: 'Return correlation by asset class',
    body: [
      'How closely each pair of asset classes has moved month to month: +1 means they rise and fall together, 0 unrelated, −1 opposite. Lower numbers between your large holdings mean better diversification.',
      'Uses price moves only, so money you add doesn’t count. Assets without price history, like deposits, aren’t shown.',
      PERIOD,
    ],
  },

  // ── Tax-loss harvesting ─────────────────────────────────────────────
  taxHarvest: {
    title: 'Cut your tax bill',
    body: [
      'Holdings currently at a loss that you could sell to book that loss and set it against capital gains this financial year, reducing your tax.',
      'These are estimates. Set-off rules and timing have conditions — check with a tax professional before acting.',
    ],
  },
  harvestLossPool: {
    title: 'Unrealised loss pool',
    body: ['The total paper loss across all holdings currently worth less than you paid.'],
  },
  harvestStcgOffset: {
    title: 'STCG offset available',
    body: [
      'Losses on holdings in the short-term bucket. Short-term losses can be set off against both short- and long-term gains.',
    ],
  },
  harvestLtcgOffset: {
    title: 'LTCG offset available',
    body: [
      'Losses on holdings in the long-term bucket. Long-term losses can only be set off against long-term gains.',
    ],
  },
  harvestRealisedFy: {
    title: 'Taxable gains (FY)',
    body: [
      `Short- and long-term gains already booked, after grandfathering and indexation — what harvested losses could offset. ${FY}`,
      'Being the taxable figure, it can differ from the book "Realised P&L (FY)" card at the top of the page.',
    ],
  },

  // ── Scenario ────────────────────────────────────────────────────────
  whatIf: {
    title: 'What-if: simulate a sale',
    body: [
      'Pick a holding and a quantity to preview a sale: proceeds, the gain or loss and whether it’s short- or long-term, estimated tax, cash left after tax, and how that holding’s share of your portfolio would change.',
      'Nothing is actually sold.',
    ],
  },
} satisfies Record<string, InfoCopy>;

export type AnalyticsInfoKey = keyof typeof ANALYTICS_INFO;
